server:
  port: 8080
  context-path: /spring-jpa
com:
  jin:
    datasource:
      master:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:7432/test
        username: zuojin
        password: 123456
      slave:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:8432/test
        username: zuojin
        password: 123456
spring:
  application:
    name: spring-jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file: ./target/spring-jpa.log